version: '2.4'
services:
  db:
    image: postgres
    container_name: webservice_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - webservice-db:/var/lib/postgresql/data

volumes:
  webservice-db: